Feature/grader UI
NUSpecialProjects/khoury-classroom-plugin pull request #72
Opened 2024-10-22 20:10 UTC by kennybc

# Checklist

- [ ] I have performed a self-review of my code
- [ ] I have reached out to another developer to review my code
- [ ] New and existing unit tests pass locally with my changes
- [ ] All Lint and CI checks are passing

2024-10-22 20:38 UTC, alexangione419 reviewed
backend looks good, want someone to look at front end still

2024-10-23 13:53 UTC, CamPlume1 commented on backend/internal/handlers/file_tree/service.go
> +func newFileService(store storage.Storage, githubappclient github.GitHubAppClient) *FileTreeService {
Capitalize N if you want it to export

2024-10-23 13:55 UTC, CamPlume1 commented on backend/internal/github/appclient/appclient.go
> +func (api *AppAPI) GetClientWithJWTAuth(ctx context.Context) (*github.Client, error) {
You shouldn't be returning a github client, this should be a struct field.

Think of it as a private field in Java with a wrapper class.

Okay as a private method if you rename with lowercase G

2024-10-23 20:54 UTC, alexangione419 requested changes

2024-10-23 20:54 UTC, alexangione419 commented on backend/internal/storage/postgres/student_assignments.go
> +		return studentAssignment, err
should prolly be nil

2024-10-23 20:54 UTC, alexangione419 commented on frontend/src/pages/Dashboard/index.tsx
> +            `${base_url}/assignments/${semester.classroom_id}`,
needs to be updated to the new route for getting all assignments with a certain classroom id

2024-10-24 13:26 UTC, nandini-ghosh reviewed
Frontend looks good, contexts make sense to me

2024-10-24 13:55 UTC, CamPlume1 approved these changes

2024-10-24 14:49 UTC, ntietje1 requested changes

2024-10-24 14:49 UTC, ntietje1 commented on backend/internal/handlers/file_tree/service.go
> +type FileTreeService struct {
Does this need to be a separate service? It seems like this is still a "github" related feature

2024-10-24 14:49 UTC, ntietje1 commented on backend/internal/handlers/semesters/assignments/assignments.go
> +		return err
What status code will this return? I think we should explicitly set them in handlers

2024-10-24 14:49 UTC, ntietje1 commented on backend/internal/handlers/semesters/assignments/assignments.go
> +	classroomID, _ := strconv.ParseInt(c.Params("classroomID"), 10, 64)
you don't handle the error case here

2024-10-24 14:49 UTC, ntietje1 commented on backend/internal/handlers/semesters/assignments/student_assignments/student_assignments.go
> +	classroomID, _ := strconv.ParseInt(c.Params("classroomID"), 10, 64)
handle error case

2024-10-24 14:49 UTC, ntietje1 commented on backend/internal/handlers/semesters/assignments/student_assignments/student_assignments.go
> +	classroomID, _ := strconv.ParseInt(c.Params("classroomID"), 10, 64)
error case

2024-10-24 14:49 UTC, ntietje1 commented on backend/internal/storage/postgres/assignments.go
> +		localAssignmentID-1)
I'd like at least a comment explaining why we have a magic "-1" here

2024-10-24 15:04 UTC, ntietje1 approved these changes
![66b3e5d0c2ab246786ca1d5e_86](https://github.com/user-attachments/assets/200bceb1-a0ba-4ca8-92a4-348c25229202)

2024-10-24 15:05 UTC, merged